### ISSUE TITLE
get other folks wanting to work on sandbox deploy keys to heroku

### ISSUE THREAD

**Issue by cmharlow** [DLFMetadataAssessment/Sandbox#1]
depends on who wants to help with sandbox changes and don't feel comfortable running changes locally then pushing to a branch christina can deploy.

**Comment by billmcmillin** [comment]
I'm fine either working on Heroku or pushing to a branch you can deploy. Whatever is easiest

**Comment by kateefly** [comment]
I haven"t worked with heroku much but would be willing to learn if this is the easiest way to work.

**Comment by billmcmillin** [comment]
If you add me to the Heroku project with billmcmillin@gmail.com I should be able to use my own key.

**Comment by cmh2166** [comment]
I'm less worried about the deploy than the theme set up right now, but i'll see if this can be a quick fix so you can do your thing, @billmcmillin

**Comment by cmh2166** [comment]
@kateefly do you want to try for heroku access as well - if so, send me the email attached to your heroku account.

**Comment by cmh2166** [comment]
to do: (eventually move to new issue) detail heroku deploy process + appropriate branch used for that

**Comment by kateefly** [comment]
Yes, give me access. My Heroku account is with kate.eileen.flynn@gmail.com

**Comment by cmh2166** [comment]
eileen, i had no idea :-)

**Comment by cmh2166** [comment]
sorry, you've both been added

**Comment by cmh2166** [comment]
not going to close in case others join later who want access, but will mark an open question and move to group column
