### ISSUE TITLE
Migrate, update & review Benchmarks page

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#102]
Currently in Child repository: https://github.com/DLFMetadataAssessment/MetadataBenchmarks

**Comment by kateefly** [comment]
Resolved with commit 894576e18b486a78f140353744b280be19ca0afb

**Comment by kateefly** [comment]
Adding more text to the beginning stating that the survey is now closed and that analysis is ongoing.

**Comment by akhtars** [comment]
How about changing the paragraphs under `Metadata Benchmarks Survey` from:

> As a part of the Digital Library Federation Forum Assessment Interest Group Metadata Working Group, the Metadata Quality Benchmarks subgroup created this survey to investigate metadata quality and how it is measured in libraries, archives, and museums. The goal of this survey is to gain insight into participant’s methods and criteria for evaluating metadata quality and to identify potential gaps in present knowledge and practices. The survey was open May 23, 2019 - July 10, 2019 and is now closed.
> 
> This survey is open to anyone self-identifying as a metadata professional who is currently employed in a library, archive, museum or other cultural heritage institution. Specifically, eligible participants for this study will be individuals with some responsibility for metadata management and/or creation for a digital repository.
>
>A <a href="../assets/Survey%20of%20Metadata%20Quality%20Benchmarks.pdf">PDF preview of the survey is available for review</a>.

to (changes highlighted):

>***This survey was open May 23-July 10, 2019 and responses are being analyzed.***
>
> As a part of the Digital Library Federation Forum Assessment Interest Group Metadata Working Group, the Metadata Quality Benchmarks subgroup created this survey to investigate metadata quality and how it is measured in libraries, archives, and museums. The goal of this survey ~~is~~*was* to gain insight into participant’s methods and criteria for evaluating metadata quality and to identify potential gaps in present knowledge and practices. ~~The survey was open May 23, 2019 - July 10, 2019 and is now closed.~~
> 
> This survey ~~is~~*was* open to anyone self-identifying as a metadata professional who is currently employed in a library, archive, museum or other cultural heritage institution. Specifically, eligible participants for this study ~~will be~~*were* individuals with some responsibility for metadata management and/or creation for a digital repository.
>
>A <a href="../assets/Survey%20of%20Metadata%20Quality%20Benchmarks.pdf">PDF ~~preview~~*copy* of the survey is available ~~for review~~</a>.

Would that be sufficient?

**Comment by kateefly** [comment]
That works for me! Thanks @akhtars

**Comment by kateefly** [comment]
Hi @akhtars - did you push this changes up Github?

**Comment by akhtars** [comment]
Apologies, just did that, opening a new pull request now.

**Comment by kateefly** [comment]
Resolved by commit cda4ef15609aa2a50279ffa0452d00b141c287d7
