### ISSUE TITLE
Connect repository to Heroku?

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#14]
There's an option in Heroku that woud (dlfaigmwgdev->deploy) that would allow us to connect the Heroku version of the site directly to this repository. This would allow us to deploy from the repository instead of from Heroku CLI.

**Comment by kateefly** [comment]
Taking a look at the repository, it seems that the site was previously deployed to Heroku using Rake. Is that right @cmh2166?

**Comment by cmh2166** [comment]
Deploy steps (I think) are there: https://gist.github.com/alexilyaev/bd4a77024ba07931907a

christina + kate will work on today

**Comment by cmh2166** [comment]
set up auto-deploy in heroku (linked to master branch)
