### ISSUE TITLE
Update Publications & Presentations of Note page

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#168]
The Publications list on https://dlfmetadataassessment.github.io/Sandbox/Publications is not the correct publications list. We would not be moving the citations list over - that is part of the legacy page. It should be this section: https://dlfmetadataassessment.github.io/EnvironmentalScan#pubs down to where the Tools section starts.

The Presentations should be the content from https://dlfmetadataassessment.github.io/EnvironmentalScan#presentations down to where Publications start.

Assign to Mike B. once added to org

**Comment by kateefly** [comment]
Change presentation list to list of citations.

**Comment by mbolam** [comment]
@kateefly --- I'm failing hard at Git stuff, I think?! I made the changes to publication.md and thought I pushed, but I think maybe I was in master, not the issue I was trying to fix. Sorry if I screwed everything up. I'm still getting used to this. Any suggestions?

**Comment by kateefly** [comment]
Resolved by commit 6f47b57e5b71674a62cefcc96b687929c55ca7de
