### ISSUE TITLE
Update 2020 contributors on Contributors

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#171]
Assign to Rachel W.

**Comment by northernlibrarian** [comment]
Shaun Akhtar
Linda Ballinger
Mike Bolam
Jennifer Bradshaw
Madison Chartier (co-facilitator, Metadata Working Group)
Jane Darcovich
Graham Dethmers
Felicity Dykas
David Erlandson
Kate Flynn (leader, Website subgroup)
Steven Gentry
Jeff Gerhard
Gretchen Gueguen
Katrina Gertz
Scott Goldstein
Kathryn Gronsbell
Gabi Gulya
Meredith Hale
Teresa Hebron
Jeannette Ho
Rachel Jaffe	
gwyn johns
Heajin Kim
Annamarie Klose (leader, Tools subgroup)
Tricia Lampron
Xiaoli Ma
Greer Martin
Mandy Mastrovita
Jane Monson
Paige Morfitt
Amelia Mowry
Anna Neatrour
Wen Nie Ng
Rebecca Pattillo
Andrea Payant
Carolyn Pecoskie
Alexandra Provo
Erik Radio
Benjamin Riesenberg
Staci Ross
Mandy Ryan
Sara Rubinow (co-leader, Assessment Interest Group)
Jacob Shelby
Gina Strack
Martha Stuit
Hannah Tarver (co-facilitator, Metadata Working Group)
Tammy Troup
Alexander Whelan
Rachel White 
Rachel Wittmann (leader, Metadata Quality Benchmarks subgroup)

**Comment by northernlibrarian** [comment]
Current and approved as of 3/22/21
