### ISSUE TITLE
re-organize website structure, leave filler text where doesn't already exist

### ISSUE THREAD

**Issue by cmharlow** [DLFMetadataAssessment/Sandbox#2]
index.md: Introduction, Scoping, Overview (2016-2017)
- DLF AIG Parent Organization
- Quality versus Assessment
- Procedure for public feedback + updates
- Areas of past, current & proposed work

Why.md: Importance of Metadata Assessment (2017?)
- Proposed collaboration project with Analytics group
- Have filler section for now with proposed work mentioned

Scan.md: Environmental scan (2016)
- Procedure for updates (link to above)
- Zotero Usage - expand?

Framework.md: Metadata assessment metrics (2016)
- Relate to origin in discussions of “quality” and environmental scan
- Also related to work on 
- Relate to discussions/review of other work - including Europeana QA

Framework.md?: Use cases for Metadata Assessment (2016)
- Originally meant to inform metadata assessment framework, give areas to target
- Responses / limitation thereof

Framework.md: Framework for performing metadata assessment // generic checklist for guidance (2016-?)
- Should build off of above work and parallel work below

Tools.md: Expanded tools recommendations (2016-?)
- Take work that fed into Environmental Scan and expand
- Site page will embed or link to Clearinghouse search interface

Profiles.md: Metadata profiles and mappings Clearinghouse (2017)
- Site page will embed or link to Clearinghouse search interface

Collaborations.md: Collaborations with Other Groups (2017)

Glossary.md: Glossary & References (2016-7)

Contact & Get Involved (exists)

About (exists)

Sidebar with site structure (exists)

**Comment by cmh2166** [comment]
break this out into some kinda gist or document to comment on? good repo docs maybe for site + theme rewrite planning?

**Comment by cmh2166** [comment]
will create this as SiteOutline.md + add to top level of repo for documentation + clarity purposes.

**Comment by cmh2166** [comment]
Update: re-writing where appropriate the main sandbox content (removing stuff that goes into project or "child" repos), and hand-coding (or updating the hand-coded) nav bar for child projects

**Comment by cmh2166** [comment]
Use nav bar to find broken links post this update (break into new issue)

**Comment by cmh2166** [comment]
working on outlining steps here (then will be broken out into issues / actionable next steps): folks please add to before next Monday July 17th

**Comment by jlhardes** [comment]
Contributors is a section off the main menu that should go to an HTML page but that page doesn't currently exist. SiteOutline.md doesn't have anything for Contributors so is that no longer part of the top level menu?

If contributors.html needs to be created, I can create an issue for that and work on it.

Still working my way through understanding what to do here, so sorry if this is something that was discussed and I missed it.

**Comment by kateefly** [comment]
@jlhardes I think contributors originally came from the Environmental Scan and the 2016 version will be included there instead (see https://github.com/DLFMetadataAssessment/EnvironmentalScan/blob/master/_entries/37contributors.md). 

However, I think we could have a 2017 contributors page that may be more appropriate as part of the top level menu. Thoughts?

**Comment by kateefly** [comment]
Contributors at top level (in Sandbox), divided by year.
