### ISSUE TITLE
Illinois Digital Heritage Hub MAP clearinghouse page

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#216]

**Comment by GentrySteven** [comment]
institution page added; metadata spec page needs to be added

**Comment by kateefly** [comment]
Hi @GentrySteven the University of Louisville page isn't showing any links/content. Otherwise everything seems to have moved ok.

There's also a larger issue that these pages don't have a layout but I'd rather address this by having a default layout in the config.yml file rather than having to go back and add it (and this was my bad). Just noting it here so I don't forget.

**Comment by kateefly** [comment]
Whoop wrong place for that last comment! Moving it.

**Comment by kateefly** [comment]
Resolved by commit c004b64f59cae81bdd168e0d10e1abfb5f57bbcf
