### ISSUE TITLE
get screencast / docs for pulling, reviewing, approving + merging a PR

### ISSUE THREAD

**Issue by cmh2166** [DLFMetadataAssessment/Sandbox#24]

**Comment by kateefly** [comment]
@f8f8ff @scottythered @jlhardes Screencast is up here:  [https://youtu.be/3fqsS2_ahXM](https://youtu.be/3fqsS2_ahXM). Hopefully it's not too bad! Let me know if you have any questions.

Here is some useful documentation as well:

- [https://git-scm.com/docs/git-remote](https://git-scm.com/docs/git-remote)
- [https://git-scm.com/docs/git-branch](https://git-scm.com/docs/git-branch)
- [https://git-scm.com/docs/git-merge](https://git-scm.com/docs/git-merge)
- [https://stackoverflow.com/questions/17189959/how-do-i-checkout-with-git-a-branch-on-a-fork-of-my-origin](https://stackoverflow.com/questions/17189959/how-do-i-checkout-with-git-a-branch-on-a-fork-of-my-origin)
