### ISSUE TITLE
Finalizing the MAP Clearinghouse Move

### ISSUE THREAD

**Issue by GentrySteven** [DLFMetadataAssessment/Sandbox#247]
The person performing this task should:

- [x] Confirm that the files in these folders conform to our naming conventions for files created by us.
- [ ] Do any necessary data clean-up (e.g. SG noticed that both "best-practice**S**" AND "best-practice" values have been put in the "type" field because that's what was used in original JSON's "tag" fields. So do we need to fix this? Same, e.g., with **PDF** and **pdf** in the "kind" fields).

**Comment by kateefly** [comment]
I did an initial review and added a new issue based on my review. It's https://github.com/DLFMetadataAssessment/Sandbox/issues/256
