### ISSUE TITLE
Apply layouts to institution pages

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#252]

**Comment by kateefly** [comment]
Institution pages don't have any layout set. We may be able to get around this with setting a default layout in the config file: https://jekyllrb.com/docs/configuration/front-matter-defaults/

**Comment by plampron2** [comment]
I attempted setting a default layout in _config.yml - #254 . I'm not sure how to actually test if that works though (it didn't break anything as far as I can see!) - if this doesn't work to fix this issue let me know and I'll just add the layouts to each page!
