### ISSUE TITLE
Links update on _metadata_specs/index.html

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#258]
Currently the links to the "Browse by institution" and "Browse by type" pages lead to 404 pages since they don't include /Sandbox/ in their URL. The links do work if you type them in manually.

**Comment by plampron2** [comment]
see pull request #260 - "Fixes issue #258"

**Comment by kateefly** [comment]
Resolved by commit ea342ee6b0a76a9faafb178120b8a5073e858fe7
