### ISSUE TITLE
Applying Styling, Structural, etc. Changes Across Site Repos

### ISSUE THREAD

**Issue by cmharlow** [DLFMetadataAssessment/Sandbox#27]

**Comment by kateefly** [comment]
Check before things go live that styling/structure is ok

**Comment by kateefly** [comment]
Please have done by 10/10 at the latest (for most glaring mistakes)

**Comment by kateefly** [comment]
My style check found that the index text hadn't been updated but no other issues that weren't already documented. The index was updated with commit 309d507ffff5aa27cb7977ff3ece318d69ee8340.

We'll want to double check the navigation (if clicking on links opens up a new window) and the headers when all prs have been merged as these have been persistent issues.
