### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#276]
@chrisDay50  will upload here and @kateefly will upload to new assets folder

**Comment by chrisDay50** [comment]
Here are the two updated logos. File names may be new, but felt appropriate.

![dlf-aig-mag_200px](https://user-images.githubusercontent.com/97248988/188640507-41713fe0-38ac-4d14-b72d-50964dbfb47b.png)
![dlf-aig-mag_Full](https://user-images.githubusercontent.com/97248988/188640510-836c5069-cd34-4915-a311-893691ecfe09.png)
