### ISSUE TITLE
Benchmarks issues

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#282]
Currently broken - points to main site instead of Sandbox

**Comment by kateefly** [comment]
As noted above, the link to the benchmark page is currently broken. The other issues were noted as well:

The link to the survey data spreadsheet is broken - See https://github.com/DLFMetadataAssessment/DLFMetadataAssessment.github.io/issues/121

The Benchmarks survey is in Archived projects but it is an ongoing one - See https://github.com/DLFMetadataAssessment/DLFMetadataAssessment.github.io/issues/129

**Comment by GentrySteven** [comment]
Found the issue with the "Benchmarks" page - the "relative url" reference had accidentally been spelled as relative*-*url instead of relative*_*url. It loads for me now.

**Comment by kateefly** [comment]
Resolved with commit 37798a6b631545493726a7428268bf0389dd6da8
