### ISSUE TITLE
Update MAP clearinghouse link to match current structure

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#285]
The current URL in Sandbox is https://dlfmetadataassessment.github.io/Sandbox/projects/metadata-application-profiles/

However the current URL on the project site is https://dlfmetadataassessment.github.io/MetadataSpecsClearinghouse/

So when we make the switch, any previous links on other sites won't go to the right place. The URL in the front matter should be customized to match this current UR. The current repository will also need to be unpublished but that can happen prior to moving the Sandbox repo to main.

**Comment by sgolds15** [comment]
I will experiment with the jekyll-redirect-from gem, which appears to be included in the github-pages gem. If that works, we can keep the current URL and make sure /MetadataSpecsClearinghouse and its children redirect to the new URL.
