### ISSUE TITLE
Info if needed for creation of Framework Project Repo

### ISSUE THREAD

**Issue by cmh2166** [DLFMetadataAssessment/Sandbox#29]
Outline of info for Framework, close issue once Framework Repo is ready / if not needed according to Framework leaders

DRAFT
This is our third area of work for the 2016 DLF Metadata Assessment group.
Being written. Includes reviewing, prioritizing the following:
Metadata quality dimension definitions
Generic checklist for guidance
Domain and jargon translations
Use cases which were collected to build framework
The following uses the other areas of work to then show how to apply these guidelines
METADATA ASSESSMENT METRICS

Build off work from 2016, involve Cultural Heritage group for second-level review
USE CASES

Build off work from 2016, involve Collaboration partners for other needs to target our assessment guidelines.
CHECKLIST

Checklist for trying to review the above metrics to assess according to the above use cases.
Holder space for whatever this becomes.

**Comment by billmcmillin** [comment]
Repo is up and content is in production/pending review
