### ISSUE TITLE
explore current jekyll theme for applicability to multi-page site

### ISSUE THREAD

**Issue by cmh2166** [DLFMetadataAssessment/Sandbox#3]

**Comment by kateefly** [comment]
Did you use a theme for the previous look/feel of the site? I don't see one specified in the config file.

**Comment by cmh2166** [comment]
yes. the config is part of a jekyll theme

**Comment by cmh2166** [comment]
this was our copied theme source: https://github.com/griffey/15-Lessons

**Comment by cmh2166** [comment]
the biggest question here is creating the appropriate templates in our site/theme + reconfiguring for jekyll generation. this isn't about themes like with wordpress or others, but how that header metadata changes, what gets served, etc. (i.e. it's not all 'posts' or static html pages)

**Comment by kateefly** [comment]
Ah thanks. I was trying to see how the theme worked (and to see how difficult it would be to change if need be) and didn't see it in the config file at all. Thanks for the link/clarification!

**Comment by cmh2166** [comment]
based on that structure, we'll then need to plan a jekyll rewrite.

**Comment by cmh2166** [comment]
possibly helpful https://github.com/mattgemmell/Jekyll-Multipage  depending on outcome of #2

**Comment by cmh2166** [comment]
help with understanding collections, pages, posts: http://ben.balter.com/2015/02/20/jekyll-collections/

another multi-page non blog site work checking out for reuse: https://github.com/github/training-kit
