### ISSUE TITLE
Create entries for parts of re-orged Sandbox

### ISSUE THREAD

**Issue by cmharlow** [DLFMetadataAssessment/Sandbox#30]
Expands #2 :

Create the following entries for the Sandbox site (with preliminary or basic text, doesn't need to be complete text):

- [x] About / Introduction
- [x] Why
- [ ] Glossary
- [x] Collaborations
- [x] Contact / Get Involved
- [x] Contributors

**Comment by kateefly** [comment]
See issue #36 for creation of Contributors entry

**Comment by kateefly** [comment]
See #41 for the Contact / Get Involved page

**Comment by kateefly** [comment]
@f8f8ff will tackle Glossary when it has been approved.

**Comment by kateefly** [comment]
@kateefly will take About page

**Comment by kateefly** [comment]
Collaborations links to DLF Forum workshop repository.

@kateefly will take this

**Comment by kateefly** [comment]
@kateefly will finish contributors
