### ISSUE TITLE
Update Projects page to point to blog posts on DLF website

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#309]

**Comment by agoslen** [comment]
Is this the link we should use? [https://www.diglib.org/news/](https://www.diglib.org/news/)

**Comment by kateefly** [comment]
I think perhaps we may have to - it looks like there is no one way to target the MWG posts only. https://www.diglib.org/category/assessment/ gets you most of them but also pulls in content from other AIG groups as well.

**Comment by agoslen** [comment]
I noticed the About page uses https://www.diglib.org/category/assessment/ so I'm going with that :)
