### ISSUE TITLE
Revisit / redo layout generation of index page

### ISSUE THREAD

**Issue by cmh2166** [DLFMetadataAssessment/Sandbox#31]
Extends #2 

Look at the production site's index.html and layouts to remember how the entries are pulled in as sections leveraging the Jekyll metadata (section-id, section-class, number variable).

Get the About / Introduction Entry done first as an example of leveraging the Jekyll theme metadata.

**Comment by kateefly** [comment]
We are structuring the site in a different (using entries as a collection folder) so this no longer applies.
