### ISSUE TITLE
Correct link on Presentations page - sandbox edition

### ISSUE THREAD

**Issue by agoslen** [DLFMetadataAssessment/Sandbox#322]
See also https://github.com/DLFMetadataAssessment/DLFMetadataAssessment.github.io/issues/148 

Update link for this citation on the [Publications and Presentations of Note page](https://dlfmetadataassessment.github.io/Sandbox/projects/publications/)

> Averkamp, Shawn, Matt Miller, Josh Hadro, and Sara Rubinow. “Measuring Your Metadata Preconference.” Presentations (communicative events) presented at the Code4Lib Philadelphia, March 7-10 2016, Philadelphia, PA, USA, March 7, 2016. http://digital.library.unt.edu/ark:/67531/metadc505014.

To point to this github repo: https://github.com/saverkamp/measure-metadata-workshop 

The link in the current citation is incorrect.

**Comment by plampron2** [comment]
Merged!
