### ISSUE TITLE
detail / document heroku deploy process

### ISSUE THREAD

**Issue by cmh2166** [DLFMetadataAssessment/Sandbox#6]
including branch to deploy, any possible merge issues 

see https://github.com/DLFMetadataAssessment/Sandbox/issues/1#issuecomment-292181880

**Comment by billmcmillin** [comment]
Katie took care of this with [this commit](https://github.com/DLFMetadataAssessment/Sandbox/commit/db559ee53827b717abb938f6d3d329f0c92cd641)
