### ISSUE TITLE
resolve target=_blank issue

### ISSUE THREAD

**Issue by billmcmillin** [DLFMetadataAssessment/Sandbox#63]
Jekyll build is turning target = _top into target = _blank, causing all pages to open in new windows

**Comment by kateefly** [comment]
I think it might be using the full url (including http://) that's causing this. Have you tried using `/Sandbox/entries`? That might solve it.

**Comment by billmcmillin** [comment]
That's part of the issue and relative paths would work for files within the repo, but this script is inserting target = _blank into all full URLs:
https://github.com/DLFMetadataAssessment/Sandbox/pull/64/files

Since we'll need full paths for cross-repo navigation, this should give us consistent behavior for both relative and full URLs.

**Comment by kateefly** [comment]
Ah I see! Good catch! I tested the change and it worked for me. Resolved with commit ab9a8a01cf8e0bd63367407f698a2f00e10cc65c
