### ISSUE TITLE
github pages not building site

### ISSUE THREAD

**Issue by billmcmillin** [DLFMetadataAssessment/Sandbox#66]
Still publishing previous builds.
May be related to submodule errors: https://help.github.com/articles/troubleshooting-github-pages-builds/

**Comment by kateefly** [comment]
Do you think this would be resolved if we removed the submodules?

**Comment by billmcmillin** [comment]
Possibly. First, I'll try to re-initialize the submodules.

**Comment by kateefly** [comment]
Sounds good. Ping me if you need me to test anything.

**Comment by billmcmillin** [comment]
Neither re-initializing nor deleting and re-creating the master branch worked, so I pushed a branch with the submodules deleted

**Comment by billmcmillin** [comment]
The code from the most recent PR works fine locally, but somehow GitHub pages is serving up an old version of the _site directory. It seems a new build is not being triggered, but there are no error messages. 

I've tried taking the site down and bringing it back up. It just brings the old version back up. I'm still looking through ghpages documentation for possible fixes.

**Comment by kateefly** [comment]
I think it's taking some time to rebuild but I just cleared my cache and checked http://dlfmetadataassessment.github.io/Sandbox and it does seem to be using the most recent build now (I checked using Inspect Element on the 'Participate' link in the navigation menu to check). This build seems to have gotten rid of the navigation issue but not the header counter issue which seems to be a deeper, thornier issue which may be really built into the theme in many places. 

I'm ok with leaving that as a known issue for now (it can be worked on over the next two weeks) and releasing to the group at large for review. Thoughts? (also tagging @f8f8ff @scottythered for feedback if  they can)

**Comment by billmcmillin** [comment]
Yeah, that seems to be working. I'll continue to work on the header issue. 

Should we check in the _site dirs of all other repos to trigger rebuilds?

**Comment by kateefly** [comment]
Let's do the rebuild in commit 7a6ffdc8583fda0718652e29dd1aad876f4d9de8 and the css/nav changes in commit 8eb6fb12c638fe7147526dbe0aa590407ecd9fae so we don't get repositories too out of sync with each other. I can take Tools and Framework if you would do EnvironementalScan?

**Comment by billmcmillin** [comment]
Sounds good

**Comment by kateefly** [comment]
Commits 7a6ffdc8583fda0718652e29dd1aad876f4d9de8 and 41485c70b1677ae5107a8f9a04b90c7a62573f6d seem to have taken care of this issue.
