### ISSUE TITLE
heroku sandbox deploy doesn't show child pages

### ISSUE THREAD

**Issue by cmh2166** [DLFMetadataAssessment/Sandbox#7]
guessing its a config / jekyll serve issue with heroku cloud, so wondering if the jekyll structure/config/serve question should be handled first.

**Comment by kateefly** [comment]
I can confirm at least that you do see child pages on a local jekyll instance using a clone of this repository (I saw them when I was taking a look at how the theme worked yesterday).

**Comment by cmh2166** [comment]
yeah. me too.

**Comment by kateefly** [comment]
I think this is because it wants the href to be "pagename.html" and not simply "pagename" as it is currently in the includes navigation file.

**Comment by kateefly** [comment]
Fixed with commit 28982c9eca4ccc89067ed30bf8430f03185caad1
