### ISSUE TITLE
A few typos

### ISSUE THREAD

**Issue by akhtars** [DLFMetadataAssessment/Sandbox#71]
I noticed a few typos on the main page: `colleciton`, `mappsings`.

Under "Contributors", `attendee` should probably be `attended`.

In a separate section, "Tools", I'm unsure, but think there may be a missing paragraph break after the list, before `A working lunch session [...]`

I'm happy to submit a pull request updating these if desired. I haven't run through the Jekyll generation process yet, but I gather it goes 1) update the Markdown, 2) generate in Jekyll, 3) review the updated HTML?

Thanks to the maintainers for all your work on updating the website.

**Comment by kateefly** [comment]
Hi Shaun - I've assigned the issue to you; it would great if you were able to go ahead and make these changes. Our [ReadMe](https://github.com/DLFMetadataAssessment/Sandbox/blob/master/README.md) has information about setting up Jekyll and the general workflow for contributing to the repository including commands you can use, if you need it (the relevant portions start about midway down). Please feel free to let us know if you have any questions about contributing or need any help!

**Comment by kateefly** [comment]
Resolved with commit 6e20caaee9a0fc65f7c08d2bda0771b2178f96f1
