### ISSUE TITLE
Fix header numbering issue

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#72]
The theme we're using was originally built for an all-in-one page setup with numbering set-up to follow h1, h2 headings.

**Comment by kateefly** [comment]
This continues to persist despite working with the CSS to work things out. I've determined that what seems to be causing the problem is a [css psudeo-element](https://www.w3schools.com/CSS/css_pseudo_elements.asp) that appears right before the h1 element (you can see it by inspecting the '0' that appears before an element, it's :before). This doesn't appear to be in _site/main.css or my local instance so I can only assume it's being added **after** in some way. I'm currently looking at the js files to see if they are doing some post-processing that's causing this psuedo-element to be inserted - in particular in jquery-2.1.1.min.js lines 2277-2290, 2371-2386 seem to hint at this (though I'm no JS expert).

**Comment by billmcmillin** [comment]
It worked! Thanks for resolving this. I was out of ideas.
