### ISSUE TITLE
Review / update home page

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#94]
Should be up to date but needs to be reviewed; breadcrumbs implemented?

**Comment by GentrySteven** [comment]
Breadcrumbs probably don't need to be implemented.

Mostly minor updates after a quick review
[index.txt](https://github.com/DLFMetadataAssessment/Sandbox/files/3464620/index.txt)
--I won't be at the next meeting, but have attached a .txt file of the changes.

**Comment by kateefly** [comment]
Resolved by commit bfbc3c62b2e676de8edf0f496ac40afd43f677fe
