### ISSUE TITLE
Review / update Contributors page

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#98]
2019 contributors will need to be added. We may also want to discuss a better way of reorganizing this.

**Comment by dkulczak** [comment]
Hello all, I will go back through the minutes and get the 2019 folks added.  Then we can discuss if we want to reorganize.  Sound like a plan?

**Comment by kateefly** [comment]
Sounds great! Thanks @dkulczak

**Comment by dkulczak** [comment]
Here is the 2019 list so far.  Additions and corrections would be most welcome!

[DLF Metadata Assessment Group 2019.docx](https://github.com/DLFMetadataAssessment/Sandbox/files/3517508/DLF.Metadata.Assessment.Group.2019.docx)

**Comment by kateefly** [comment]
Fixed by commit 5cc61d24eb6535d57392cb51b1c984cd012f4c87 in the main site. Will need to make sure this information is kept during migration

**Comment by dkulczak** [comment]
I'm trying this again, because when I looked at the file I pushed last weekend, it didn't have all the info.  Will try sending through again.

**Comment by kateefly** [comment]
Could you add a permalink? Something like

`permalink: contributors`

Right below `title: contributors` in the front matter.

**Comment by kateefly** [comment]
No further requests for changes so closing this ticket.
