### ISSUE TITLE
Review / update Skillbuilding page

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/Sandbox#99]

**Comment by kgrons** [comment]
see pr #89

**Comment by kateefly** [comment]
Resolved by commit 6cab868aaeb35abb121a13f74f84b8d51038c63f

**Comment by kateefly** [comment]
Reopening because of two pieces of feedback received from the group at large:

- First is the the suggest to add anchor tags to the top of the page to help with navigation. This will also align the look with other pages that are very long (see Environmental Scan)
- Second, suggestion from @kgrons to replace [tbd] text with "This site presents a comprehensive but simplified resource for how to approach metadata assessment. In 2019, the MWG Website subgroup updated the site to run on a simplified Jekyll template, resulting in a more streamlined and unified structure. The intention was to increase usability of the site and its contents. "

**Comment by kateefly** [comment]
Resolved with commit d31e25907f38abd94660af71acf16a65e1ebd23a
